### ISSUE TITLE
请问有livere的配置教程吗？

### ISSUE THREAD

**Issue by FANUP** [fi3ework/hexo-theme-archer#17]
很喜欢archer的风格！看了作者的demo，是有请livere的评论控件的，想问一下那有livere的配置教程么？

**Comment by fi3ework** [comment]
在[主题参数配置](https://github.com/fi3ework/hexo-theme-archer)那里有
```yml
comment:
  # livere 官网：https://livere.com/
  livere_uid:
```
直接填写livere的uid的即可。
