### ISSUE TITLE
設置tags時候出現問題

### ISSUE THREAD

**Issue by rupigcute** [fi3ework/hexo-theme-archer#18]
作者你好，我成功的讓sidebar 出現了我在文章內使用的Tags，可是我點擊的時候卻沒有任何文章列表出現，請問這個問題要怎樣解決呢，謝謝。
https://imgur.com/a/SxeHC

**Comment by rupigcute** [comment]
[](https://imgur.com/a/SxeHCl)

**Comment by fi3ework** [comment]
你好，感谢使用。
看了一下你主页下的[content.json](https://rupigcute.github.io/content.json)，发现格式不太对。
是按照文档里的
```yml
jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true
```
这样写的吗:smile:
