### ISSUE TITLE
关于文章显示页面太窄的问题

### ISSUE THREAD

**Issue by HuMingGuang** [fi3ework/hexo-theme-archer#218]
由于文章内容比较多，如果显示的太窄，看起来比较难受，怎样可以调整，使显示页内容的地方变宽。

**Comment by LolipopJ** [comment]
可以尝试修改 `src/scss/_common.scss` 中的 `.main` 选择器：

```scss
.main {
  min-width: 42.8125rem; # 修改为更大的值
}
```
