### ISSUE TITLE
Tags功能和Categories功能均不显示文章

### ISSUE THREAD

**Issue by P2hm1n** [fi3ework/hexo-theme-archer#227]
**「描述遇到的问题」或「发现的 bug」（Describe the problem or bug you encounter）**
emm最近不知道用了什么hexo的更新语句，导致这个主题崩了，弄了好久终于弄好了，可是Tags功能和Categories功能均不显示文章，问题如下

个人markdown的Front-matter是这么写的
![image](https://user-images.githubusercontent.com/44919834/59096164-cfe63080-894c-11e9-82a6-116881897715.png)

然后hexo的config配置如下
```
jsonContent:
    meta: false
    pages: false
    posts:
      title: true
      date: true
      path: true
      text: false
      raw: false
      content: false
      slug: false
      updated: false
      comments: false
      link: false
      permalink: false
      excerpt: false
      categories: true
      tags: true
```

hexo的  \scaffolds\post.md配置如下
```
---
title: {{ title }}
date: {{ date }}
tags:
categories:
---
```

看了几篇相似的文章还是没有解决

尝试过的方法有：

- [x] 重新安装该主题
- [x] hexo clean
- [x] 更换不同的浏览器查看

**你是否已经阅读过以下内容，并确认你的行为是正确的，在 `[ ]` 中填入 `x` 选中（Ensure that you had consulted followings and confirm the validity of your operation, fill `x` in `[ ]` to select）**
- [x] [Hexo 文档 | Hexo document](https://hexo.io/docs/)
- [x] [Archer 文档 | hexo-theme-archer document](https://github.com/fi3ework/hexo-theme-archer)

**如何复现（To Reproduce）**

个人博客地址： https://p2hm1n.github.io/

**存在问题或 bug 的已部署上线的页面地址（A deployed page link that with bug or problem）**

个人博客地址： https://p2hm1n.github.io/

**如果可能是与 markdown 内容相关的问题或 bug，请粘贴对应的 markdown 内容（If the problem or bug that may be related to markdown, paste it here）**

**打开控制台，填写控制台中打印的主题的版本，如果脚本出错可直接提供控制台截图（Open the console and report the version of hexo-theme-archer. You can paste the screenshot on console directly if there is error with script）**

```
λ hexo version
hexo: 3.8.0
hexo-cli: 1.1.0
os: Windows_NT 10.0.17134 win32 x64
http_parser: 2.8.0
node: 10.15.2
v8: 6.8.275.32-node.12
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```

**信息 (please complete the following information):**
 - 操作系统（OS）: [e.g. iOS]
 - 浏览器（Browser） [e.g. chrome, safari]
 - 浏览器版本（Version）[e.g. 22][可选]

**其他信息（Additional context）**
