### ISSUE TITLE
gitalk not work.

### ISSUE THREAD

**Issue by RexHung0302** [fi3ework/hexo-theme-archer#251]
首先感謝作者做出這麼好的主題，非常感謝。

您好這邊設置了 gitalk 想開啟留言板，但是似乎沒有反應，相關設置如下：
```
gitalk:
  enable: false
  client_id: 2la2*****************
  client_secret: e3***************************************************
  github_id: RexHung0302 # GitHub 作者帳號
  admin_user: RexHung0302 # 管理者的帳號
  repo: zexhung0302.github.io # 你的 Repo 名稱，通常就是網域
  distraction_free_mode: ture # 無干擾模式
  owner: RexHung0302
  admin: RexHung0302
  language: zh-TW # 語系 en, zh-CN, zh-TW
  labels: Gitalk # 分類
```
不曉得是否有設置錯誤 目前設置完畢後打開發現下方會出現 評論 二字 但是就沒其他東西了。

github 的 Developer settings 那邊已經設定過了

再次感謝作者。
