### ISSUE TITLE
「反馈 Bug」steam图标偏上

### ISSUE THREAD

**Issue by ted423** [fi3ework/hexo-theme-archer#301]
**「描述遇到的问题」或「发现的 bug」（Describe the problem or bug you encounter）**

**你是否已经阅读过以下内容，并确认你的行为是正确的，在 `[ ]` 中填入 `x` 选中（Ensure that you had consulted followings and confirm the validity of your operation, fill `x` in `[ ]` to select）**
- [ ] [Hexo 文档 | Hexo document](https://hexo.io/docs/)
- [ ] [Archer 文档 | hexo-theme-archer document](https://github.com/fi3ework/hexo-theme-archer)

**如何复现（To Reproduce）**

**存在问题或 bug 的已部署上线的页面地址（A deployed page link that with bug or problem）**
![image](https://user-images.githubusercontent.com/7042766/121491123-402a5f80-ca08-11eb-9ad2-8588bd1ccaa7.png)
https://ted423.github.io/
**如果可能是与 markdown 内容相关的问题或 bug，请粘贴对应的 markdown 内容（If the problem or bug that may be related to markdown, paste it here）**

**打开控制台，填写控制台中打印的主题的版本，如果脚本出错可直接提供控制台截图（Open the console and report the version of hexo-theme-archer. You can paste the screenshot on console directly if there is error with script）**
 🎯 hexo-theme-archer ⬇️ 
main.js:3190  🏷 Version: 1.6.1 
main.js:3191  📅 Version date: 20210204

**信息 (please complete the following information):**
 - 操作系统（OS）:win和安卓看了都有问题
 - 浏览器（Browser） chrome
 - 浏览器版本（Version）[e.g. 22][可选]

**其他信息（Additional context）**

**Comment by Stark-X** [comment]
你是指 主页个人信息下方的 steam 图标吗？下次提 issue 可以一并提供截图

**Comment by ted423** [comment]
> 你是指 主页个人信息下方的 steam 图标吗？下次提 issue 可以一并提供截图

截了。。。可能太小了
https://user-images.githubusercontent.com/7042766/121491123-402a5f80-ca08-11eb-9ad2-8588bd1ccaa7.png

**Comment by Stark-X** [comment]
哦哦，昨天看的时候，图片没加载出来

**Comment by ted423** [comment]
才发现底部也有类似问题
![image](https://user-images.githubusercontent.com/7042766/124346316-ab82de00-dc10-11eb-9431-e9634ec91b1d.png)
并且能感觉到Github偏大，其本身style设置似乎大小就不一样

**Comment by LolipopJ** [comment]
对这些图标来自编码层面的处理是相同的：

``` scss
// src/scss/_variables.scss
.iconfont-archer {
  font-family: 'iconfont-archer' !important;
  font-size: 1rem;
  font-style: normal;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

// src/scss/_partial/_partial/_profile.scss
.profile-social {
  position: relative;
  width: 100%;
  text-align: left;
  line-height: 1.7rem;
  padding: 0.5rem 0;
  border-bottom: 1px solid rgba(0, 0, 0, 0.1);
  .iconfont-archer {
    position: relative;
  }
  @include social($scaleSize: 0.5, $spanMargin: 0.4rem);
}
```

问题出在 Font Awsome 图标库，对于这个库，看到有这样一个评价：

> fa iconfont 整体质量不高，更多的是以量取胜（你能想到的他基本都有）。比如大小不一的问题，有时你不得不把某些图标的字体设置的更大一些，以保证图标看起来差不多大。

这意味着，如果我们接着使用这个图标库，为了处理大小不同的问题，需要在找到基准图标后，单独为每个图标设置 CSS。

亦或是切换使用其它设计更规范的图标库，来避免这样的问题，例如 Material Design Icon，这是它的[清单](https://materialdesignicons.com/)。
