### ISSUE TITLE
添加tags和categories后，点击sidebar中tag和cate下标签没有反应，不发生跳转

### ISSUE THREAD

**Issue by hansanf** [fi3ework/hexo-theme-archer#320]
**Please ensure set `tags: true` and `categories: true` of the hexo-content-json config**
给文章添加标签后，页面能显示所添加的标签，但是点击标签页面没有反应，提示错误：
Please ensure set `tags: true` and `categories: true` of the hexo-content-json config 
在使用其他主题时没有这个问题

**如何复现（To Reproduce）**
_config.yml中的内容
```
jsonContent:
  meta: true
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: true
    excerpt: false
    categories: true
    tags: true
```

**存在问题或 bug 的已部署上线的页面地址（A deployed page link that with bug or problem）**
https://hansanf.github.io/  点开左边的sidebar中的Tag，点击下面的标签会出现上述问题

**如果可能是与 markdown 内容相关的问题或 bug，请粘贴对应的 markdown 内容（If the problem or bug that may be related to markdown, paste it here）**

**打开控制台，填写控制台中打印的主题的版本，如果脚本出错可直接提供控制台截图（Open the console and report the version of hexo-theme-archer. You can paste the screenshot on console directly if there is error with script）**

**信息 (please complete the following information):**
 - 操作系统（OS）: [e.g. iOS]
 - 浏览器（Browser） [e.g. chrome, safari]
 - 浏览器版本（Version）[e.g. 22][可选]

**其他信息（Additional context）**
