### ISSUE TITLE
algolia自动更新工作流中，pandoc依赖缺失

### ISSUE THREAD

**Issue by LuLu010722** [fi3ework/hexo-theme-archer#345]
尝试同时开启latex和algolia
按照开启algolia的教程，编写了新的workflow file，并新建了分支source，将源文件push到该分支上

但是在执行新建的actions的时候，出现了下面的问题
![image](https://user-images.githubusercontent.com/62323571/190892840-457d07a7-657a-4fa0-98d4-c50149c50539.png)

好像是因为github服务器上没有pandoc依赖，但是我不知道如何在workflow file里面下载，求教。

workflow file见下：
```yml
name: Hexo Blog CI & CD

on:
  push:
    branches:
      - source

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-cache
          restore-keys: |
            ${{ runner.os }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Get algolia objects
        run: npm run algolia
        env:
          HEXO_ALGOLIA_INDEXING_KEY: ${{ secrets.HEXO_ALGOLIA_INDEXING_KEY }}
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./public
          publish_branch: main  # deploying branch
```
