### ISSUE TITLE
怎么设置字体。下面的方式正确吗？

### ISSUE THREAD

**Issue by xiaoyangst** [fi3ework/hexo-theme-archer#403]
![image](https://github.com/user-attachments/assets/7b9d6973-2ef0-4554-af5d-51a351da3121)

![image](https://github.com/user-attachments/assets/3a48bf27-31f3-4a3c-b2d1-6338e4cebdae)

反正我没有成功

**Comment by Stark-X** [comment]
或许，你可以参考一下本主题的贡献者的博客：[为 Archer 主题更换字体](https://blog.towind.fun/20210625/web-font-for-hexo-theme-archer/)

**Comment by LolipopJ** [comment]
You can enable the custom fonts in the follow way:

```yml
custom_font:
  enable: true
  # Font name, use ':' to select font weight and font style
  name: "Noto Sans SC:n3,n4,n5,n7"
  # Font CDN url
  url: "https://cdn.jsdelivr.net/npm/fontsource-noto-sans-sc@4.0.0/chinese-simplified.css"
```

No need to modify other files.

---

The legacy url is not able to visit, I have updated the url in `README.md`. Thanks for feedback.
