### ISSUE TITLE
点击有空格的 tag 无反应

### ISSUE THREAD

**Issue by secsilm** [fi3ework/hexo-theme-archer#59]
我的有些 tag 是两个单词组成的，中间有空格，以前版本在 Tag 页点击这种 tag 还能显示出对应的文章，但是现在版本（`1.1.0`）点击之后没反应，例如下图我点击 `Machine Learning` 这个 tag：

![](https://i.imgur.com/lzyEUna.png)

然后该标签是有对应文章的，例如：

![](https://i.imgur.com/uBwmIrg.png)

**Comment by fi3ework** [comment]
@secsilm 这个确实是个bug...，过几天会fix掉🤠

**Comment by secsilm** [comment]
@fi3ework 大佬好像还是不行啊，仍然没反应，我看控制台有个报错如下，但是我已经设置了为 true 了，大佬可以去我的[网站](https://alanlee.fun/)瞅下：

```
Please ensure set `tags: true` and `categories: true` of the hexo-content-json config
```

![](https://i.imgur.com/J458WRG.png)

`_config.yml`：

```
jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: true
    excerpt: false
    categories: true
    tags: true
```
